html:
  benchmark_factor_names_step: 1000
  benchmark_factor_scores_step: 1000
  scores_step: 1000
  guides_step: 1000
  competency_step: 1000
  competency_factors_step: 1000
  training_requirements_report:
    scores_step: 10000
    graph_limiter_on_training_requirement_report: 10
    pie_charts_step: 1000
feedback:
  benchmark_factor_names_step: 1000
  benchmark_factor_scores_step: 1000
  scores_step: 1000
  guides_step: 1000
  competency_step: 1000
  competency_factors_step: 1000
  training_requirements_report:
    scores_step: 10000
pdf:
  benchmark_factor_names_step: 18
  benchmark_factor_scores_step: 3
  competency_factors_step: 3
  competency_step: 3
  scores_step: 4
  guides_step: 8
  training_requirements_report:
    scores_step: 4
    graph_limiter_on_training_requirement_report: 10
    pie_charts_step: 10
candidate:
  fitment_scores: "Fitment Scores"
  report_title: "Assessment Report"
  job_role_fit: "Job Sync"
  company_fit: "People Skills"
  team_fit: "Personal Effectiveness"
employee:
  fitment_scores: "Scores"
  report_title: "Assessment Report"
  job_role_fit: "Job Sync"
  company_fit: "People Skills"
  team_fit: "Personal Effectiveness"

engagement_report:
  less_favorable_score: 40
  
mrf_report:
  recognised_strengths: "Strengths according to the candidate as well as stakeholders. They are traits that both candidates and stakeholders have rated on the higher side. Average scores are not considered here."
  unrecognised_strengths: "Strengths according to stakeholders, but unknown to the candidate. They are traits that stakeholders have rated on the higher side, but the candidate has rated themselves on the lower side. Average scores are not considered here."
  recognised_areas_of_improvements: "Areas of improvement according to the candidate as well as stakeholders. They are traits that both candidates and stakeholders have rated on the lower side. Average scores are not considered here."
  unrecognised_areas_of_improvements: "Areas of improvement according to stakeholders, but unknown to the candidate. They are traits that stakeholders have rated on the lower side but the candidate has rated themselves on the higher side. Average scores are not considered here."
